package tong.statmod.integration.sdm;

import java.util.List;

final class SDMShopCatalogEntries {
    private SDMShopCatalogEntries() {}

    static List<SDMShopCatalog.ShopItem> items() {
        return List.of(
            // ══ Minerais bruts (×4) ══ floor 1-10 : 100-500 ══
            entry("Minerais bruts", "minecraft:coal", 100, 4),
            entry("Minerais bruts", "minecraft:raw_iron", 200, 4),
            entry("Minerais bruts", "minecraft:raw_copper", 200, 4),
            entry("Minerais bruts", "minecraft:raw_gold", 400, 4),
            entry("Minerais bruts", "iceandfire:copper_ore", 200, 4),
            entry("Minerais bruts", "iceandfire:silver_ore", 250, 4),
            entry("Minerais bruts", "iceandfire:raw_silver", 350, 4),
            entry("Minerais bruts", "iceandfire:sapphire_ore", 400, 4),
            entry("Minerais bruts", "iceandfire:deepslate_silver_ore", 300, 4),
            entry("Minerais bruts", "irons_spellbooks:mithril_ore", 400, 4),
            entry("Minerais bruts", "irons_spellbooks:raw_mithril", 500, 4),
            entry("Minerais bruts", "irons_spellbooks:deepslate_mithril_ore", 500, 4),
            entry("Minerais bruts", "tensura:magic_ore", 400, 4),
            entry("Minerais bruts", "tensura:deepslate_magic_ore", 500, 4),
            entry("Minerais bruts", "tensura:deepslate_silver_ore", 300, 4),
            entry("Minerais bruts", "tensura:raw_armorsaurus_meat", 300, 4),
            entry("Minerais bruts", "tensura:raw_blade_tiger_meat", 300, 4),
            entry("Minerais bruts", "tensura:raw_giant_bat_meat", 200, 4),
            entry("Minerais bruts", "tensura:raw_charybdis_meat", 500, 4),
            entry("Minerais bruts", "farmersdelight:raw_pasta", 150, 4),

            // ══ Lingots et gemmes (×2) ══ floor 10-40 : 400-10000 ══
            entry("Lingots et gemmes", "minecraft:iron_ingot", 400, 2),
            entry("Lingots et gemmes", "minecraft:copper_ingot", 400, 2),
            entry("Lingots et gemmes", "minecraft:gold_ingot", 600, 2),
            entry("Lingots et gemmes", "minecraft:diamond", 2500, 2),
            entry("Lingots et gemmes", "minecraft:emerald", 600, 2),
            entry("Lingots et gemmes", "minecraft:netherite_ingot", 12000, 2),
            entry("Lingots et gemmes", "minecraft:quartz", 400, 2),
            entry("Lingots et gemmes", "minecraft:redstone", 400, 2),
            entry("Lingots et gemmes", "minecraft:lapis_lazuli", 500, 2),
            entry("Lingots et gemmes", "minecraft:amethyst_shard", 500, 2),
            entry("Lingots et gemmes", "iceandfire:copper_ingot", 500, 2),
            entry("Lingots et gemmes", "iceandfire:silver_ingot", 600, 2),
            entry("Lingots et gemmes", "iceandfire:sapphire_gem", 800, 2),
            entry("Lingots et gemmes", "iceandfire:amythest_gem", 800, 2),
            entry("Lingots et gemmes", "iceandfire:ghost_ingot", 800, 2),
            entry("Lingots et gemmes", "iceandfire:dragonsteel_fire_ingot", 10000, 2),
            entry("Lingots et gemmes", "iceandfire:dragonsteel_ice_ingot", 10000, 2),
            entry("Lingots et gemmes", "iceandfire:dragonsteel_lightning_ingot", 10000, 2),
            entry("Lingots et gemmes", "irons_spellbooks:mithril_ingot", 800, 2),
            entry("Lingots et gemmes", "irons_spellbooks:arcane_ingot", 1000, 2),
            entry("Lingots et gemmes", "irons_spellbooks:pyrium_ingot", 800, 2),
            entry("Lingots et gemmes", "magistuarmory:tin_ingot", 300, 2),
            entry("Lingots et gemmes", "magistuarmory:bronze_ingot", 400, 2),
            entry("Lingots et gemmes", "magistuarmory:silver_ingot", 600, 2),
            entry("Lingots et gemmes", "magistuarmory:steel_ingot", 700, 2),
            entry("Lingots et gemmes", "tensura:silver_ingot", 600, 2),
            entry("Lingots et gemmes", "tensura:orichalcum_ingot", 1500, 2),
            entry("Lingots et gemmes", "tensura:high_magisteel_ingot", 3000, 2),
            entry("Lingots et gemmes", "tensura:pure_magisteel_ingot", 6000, 2),
            entry("Lingots et gemmes", "tensura:mithril_ingot", 2000, 2),
            entry("Lingots et gemmes", "tensura:adamantite_ingot", 10000, 2),
            entry("Lingots et gemmes", "tensura:hihiirokane_ingot", 12000, 2),
            entry("Lingots et gemmes", "tensura:magic_ore_ingot", 500, 2),
            entry("Lingots et gemmes", "tensura:low_magisteel_ingot", 1500, 2),
            entry("Lingots et gemmes", "simplyswords:netherfused_gem", 1000, 2),
            entry("Lingots et gemmes", "simplyswords:runefused_gem", 1000, 2),

            // ══ Matériaux avancés (×1) ══ floor 15-60 : 1500-10000 ══
            entry("Matériaux avancés", "apotheosis:rare_material", 4000, 1),
            entry("Matériaux avancés", "apotheosis:epic_material", 6000, 1),
            entry("Matériaux avancés", "apotheosis:mythic_material", 12000, 1),
            entry("Matériaux avancés", "apotheosis:gems/external/mycotoxin_crystal", 3000, 1),
            entry("Matériaux avancés", "minecraft:netherite_scrap", 8000, 1),
            entry("Matériaux avancés", "iceandfire:dragonbone", 4000, 1),
            entry("Matériaux avancés", "iceandfire:witherbone", 2500, 1),
            entry("Matériaux avancés", "iceandfire:wither_shard", 2500, 1),
            entry("Matériaux avancés", "iceandfire:dread_shard", 2500, 1),
            entry("Matériaux avancés", "irons_spellbooks:arcane_essence", 2500, 1),
            entry("Matériaux avancés", "irons_spellbooks:cinder_essence", 2500, 1),
            entry("Matériaux avancés", "irons_spellbooks:permafrost_shard", 2500, 1),
            entry("Matériaux avancés", "irons_spellbooks:ancient_knowledge_fragment", 4000, 1),
            entry("Matériaux avancés", "irons_spellbooks:dead_king_phylactery_shard", 6000, 1),
            entry("Matériaux avancés", "mutantmonsters:creeper_shard", 2500, 1),
            entry("Matériaux avancés", "mutantmonsters:mutant_skeleton_shoulder", 2500, 1),
            entry("Matériaux avancés", "overgeared:diamond_shard", 5000, 1),
            entry("Matériaux avancés", "overgeared:netherite_alloy", 10000, 1),
            entry("Matériaux avancés", "overgeared:heated_netherite_alloy", 10000, 1),
            entry("Matériaux avancés", "statmod:epic_physical_shard", 5000, 1),
            entry("Matériaux avancés", "statmod:epic_magical_shard", 5000, 1),
            entry("Matériaux avancés", "statmod:epic_agile_shard", 5000, 1),
            entry("Matériaux avancés", "statmod:epic_spiritual_shard", 5000, 1),

            // ══ Forge et amélioration (×1) ══ floor 10-40 : 1000-4000 ══
            entry("Forge et amélioration", "apotheosis:iron_upgrade_smithing_template", 1200, 1),
            entry("Forge et amélioration", "apotheosis:gold_upgrade_smithing_template", 2000, 1),
            entry("Forge et amélioration", "apotheosis:diamond_upgrade_smithing_template", 4000, 1),
            entry("Forge et amélioration", "apotheosis:gem_dust", 2000, 1),
            entry("Forge et amélioration", "apotheosis:sigil_of_enhancement", 2500, 1),
            entry("Forge et amélioration", "apotheosis:sigil_of_supremacy", 2500, 1),
            entry("Forge et amélioration", "apotheosis:sigil_of_rebirth", 2500, 1),
            entry("Forge et amélioration", "apotheosis:sigil_of_malice", 2500, 1),
            entry("Forge et amélioration", "apotheosis:sigil_of_unnaming", 2500, 1),
            entry("Forge et amélioration", "apotheosis:sigil_of_withdrawal", 2500, 1),
            entry("Forge et amélioration", "apotheosis:sigil_of_socketing", 4000, 1),
            entry("Forge et amélioration", "iceandfire:dragonarmor_iron_head", 2000, 1),
            entry("Forge et amélioration", "iceandfire:dragonarmor_copper_head", 3000, 1),
            entry("Forge et amélioration", "iceandfire:dragonarmor_gold_head", 3000, 1),
            entry("Forge et amélioration", "iceandfire:dragonarmor_diamond_head", 5000, 1),
            entry("Forge et amélioration", "iceandfire:dragonarmor_dragon_steel_fire_head", 12000, 1),
            entry("Forge et amélioration", "iceandfire:dragonarmor_dragon_steel_ice_head", 12000, 1),
            entry("Forge et amélioration", "iceandfire:dragonarmor_dragon_steel_lightning_head", 12000, 1),
            entry("Forge et amélioration", "iceandfire:banner_pattern_fire_head", 1500, 1),
            entry("Forge et amélioration", "iceandfire:banner_pattern_ice_head", 1500, 1),
            entry("Forge et amélioration", "iceandfire:banner_pattern_lightning_head", 1500, 1),
            entry("Forge et amélioration", "iceandfire:banner_pattern_hippogryph_head", 1500, 1),

            // ══ Armes légères (×1) ══ floor 5-50 : 800-18000 ══
            entry("Armes légères", "epicfight:wooden_dagger", 800, 1),
            entry("Armes légères", "epicfight:wooden_tachi", 1000, 1),
            entry("Armes légères", "epicfight:stone_dagger", 1200, 1),
            entry("Armes légères", "epicfight:stone_tachi", 1500, 1),
            entry("Armes légères", "epicfight:bokken", 1000, 1),
            entry("Armes légères", "epicfight:iron_dagger", 2000, 1),
            entry("Armes légères", "epicfight:iron_tachi", 2500, 1),
            entry("Armes légères", "epicfight:golden_dagger", 2000, 1),
            entry("Armes légères", "epicfight:golden_tachi", 2500, 1),
            entry("Armes légères", "epicfight:uchigatana", 3000, 1),
            entry("Armes légères", "epicfight:diamond_dagger", 5000, 1),
            entry("Armes légères", "epicfight:diamond_tachi", 6000, 1),
            entry("Armes légères", "epicfight:netherite_dagger", 15000, 1),
            entry("Armes légères", "epicfight:netherite_tachi", 18000, 1),
            entry("Armes légères", "iceandfire:stymphalian_bird_dagger", 3000, 1),
            entry("Armes légères", "irons_spellbooks:amethyst_rapier", 3000, 1),
            entry("Armes légères", "irons_spellbooks:fiery_dagger", 3000, 1),
            entry("Armes légères", "irons_spellbooks:obsidian_katana", 3000, 1),
            entry("Armes légères", "simplyswords:iron_katana", 2500, 1),
            entry("Armes légères", "simplyswords:iron_cutlass", 2500, 1),
            entry("Armes légères", "simplyswords:iron_rapier", 2500, 1),
            entry("Armes légères", "simplyswords:iron_sai", 2500, 1),
            entry("Armes légères", "simplyswords:iron_warglaive", 2500, 1),
            entry("Armes légères", "simplyswords:gold_katana", 2000, 1),
            entry("Armes légères", "simplyswords:gold_cutlass", 2000, 1),
            entry("Armes légères", "simplyswords:gold_rapier", 2000, 1),
            entry("Armes légères", "simplyswords:gold_sai", 2000, 1),
            entry("Armes légères", "simplyswords:diamond_katana", 5000, 1),
            entry("Armes légères", "simplyswords:diamond_cutlass", 5000, 1),
            entry("Armes légères", "simplyswords:diamond_rapier", 5000, 1),
            entry("Armes légères", "simplyswords:diamond_sai", 5000, 1),
            entry("Armes légères", "simplyswords:diamond_warglaive", 5000, 1),
            entry("Armes légères", "simplyswords:netherite_katana", 15000, 1),
            entry("Armes légères", "simplyswords:netherite_cutlass", 15000, 1),
            entry("Armes légères", "simplyswords:netherite_rapier", 15000, 1),
            entry("Armes légères", "simplyswords:netherite_sai", 15000, 1),
            entry("Armes légères", "simplyswords:netherite_warglaive", 15000, 1),

            // ══ Armes lourdes (×1) ══ floor 10-60 : 1200-25000 ══
            entry("Armes lourdes", "epicfight:wooden_longsword", 1200, 1),
            entry("Armes lourdes", "epicfight:wooden_greatsword", 1500, 1),
            entry("Armes lourdes", "epicfight:stone_longsword", 1800, 1),
            entry("Armes lourdes", "epicfight:stone_greatsword", 2000, 1),
            entry("Armes lourdes", "epicfight:iron_longsword", 3000, 1),
            entry("Armes lourdes", "epicfight:iron_greatsword", 3500, 1),
            entry("Armes lourdes", "epicfight:greatsword", 3500, 1),
            entry("Armes lourdes", "epicfight:golden_longsword", 2800, 1),
            entry("Armes lourdes", "epicfight:golden_greatsword", 3000, 1),
            entry("Armes lourdes", "epicfight:diamond_longsword", 6500, 1),
            entry("Armes lourdes", "epicfight:diamond_greatsword", 7000, 1),
            entry("Armes lourdes", "epicfight:netherite_longsword", 20000, 1),
            entry("Armes lourdes", "epicfight:netherite_greatsword", 22000, 1),
            entry("Armes lourdes", "irons_spellbooks:decrepit_scythe", 3500, 1),
            entry("Armes lourdes", "irons_spellbooks:stone_scythe", 3500, 1),
            entry("Armes lourdes", "mutantmonsters:hulk_hammer", 3500, 1),
            entry("Armes lourdes", "simplyswords:brimstone_claymore", 3500, 1),
            entry("Armes lourdes", "simplyswords:iron_claymore", 3000, 1),
            entry("Armes lourdes", "simplyswords:iron_greataxe", 3000, 1),
            entry("Armes lourdes", "simplyswords:iron_greathammer", 3500, 1),
            entry("Armes lourdes", "simplyswords:iron_longsword", 3000, 1),
            entry("Armes lourdes", "simplyswords:iron_scythe", 3000, 1),
            entry("Armes lourdes", "simplyswords:gold_claymore", 2500, 1),
            entry("Armes lourdes", "simplyswords:diamond_claymore", 6500, 1),
            entry("Armes lourdes", "simplyswords:diamond_greataxe", 7000, 1),
            entry("Armes lourdes", "simplyswords:diamond_greathammer", 7000, 1),
            entry("Armes lourdes", "simplyswords:diamond_longsword", 6500, 1),
            entry("Armes lourdes", "simplyswords:diamond_scythe", 6000, 1),
            entry("Armes lourdes", "simplyswords:netherite_claymore", 20000, 1),
            entry("Armes lourdes", "simplyswords:netherite_greataxe", 22000, 1),
            entry("Armes lourdes", "simplyswords:netherite_greathammer", 22000, 1),
            entry("Armes lourdes", "simplyswords:netherite_longsword", 20000, 1),
            entry("Armes lourdes", "simplyswords:netherite_scythe", 18000, 1),
            entry("Armes lourdes", "magistuarmory:wood_claymore", 1500, 1),
            entry("Armes lourdes", "magistuarmory:stone_claymore", 2000, 1),
            entry("Armes lourdes", "magistuarmory:tin_claymore", 2000, 1),
            entry("Armes lourdes", "magistuarmory:copper_claymore", 2500, 1),
            entry("Armes lourdes", "magistuarmory:bronze_claymore", 2800, 1),
            entry("Armes lourdes", "magistuarmory:iron_claymore", 3000, 1),
            entry("Armes lourdes", "magistuarmory:gold_claymore", 2500, 1),
            entry("Armes lourdes", "magistuarmory:silver_claymore", 3500, 1),
            entry("Armes lourdes", "magistuarmory:steel_claymore", 3500, 1),
            entry("Armes lourdes", "magistuarmory:diamond_claymore", 6500, 1),
            entry("Armes lourdes", "magistuarmory:netherite_claymore", 20000, 1),

            // ══ Lances et armes d'hast (×1) ══ floor 10-55 : 1200-18000 ══
            entry("Lances et armes d'hast", "epicfight:wooden_spear", 1200, 1),
            entry("Lances et armes d'hast", "epicfight:stone_spear", 1800, 1),
            entry("Lances et armes d'hast", "epicfight:iron_spear", 2800, 1),
            entry("Lances et armes d'hast", "epicfight:spear", 2800, 1),
            entry("Lances et armes d'hast", "epicfight:golden_spear", 2200, 1),
            entry("Lances et armes d'hast", "epicfight:diamond_spear", 5500, 1),
            entry("Lances et armes d'hast", "epicfight:netherite_spear", 18000, 1),
            entry("Lances et armes d'hast", "iceandfire:fishing_spear", 2500, 1),
            entry("Lances et armes d'hast", "magistuarmory:wood_ahlspiess", 1200, 1),
            entry("Lances et armes d'hast", "magistuarmory:wood_guisarme", 1200, 1),
            entry("Lances et armes d'hast", "magistuarmory:stone_ahlspiess", 1800, 1),
            entry("Lances et armes d'hast", "magistuarmory:stone_guisarme", 1800, 1),
            entry("Lances et armes d'hast", "magistuarmory:tin_ahlspiess", 1800, 1),
            entry("Lances et armes d'hast", "magistuarmory:tin_guisarme", 1800, 1),
            entry("Lances et armes d'hast", "magistuarmory:copper_ahlspiess", 2200, 1),
            entry("Lances et armes d'hast", "magistuarmory:copper_guisarme", 2200, 1),
            entry("Lances et armes d'hast", "magistuarmory:bronze_ahlspiess", 2500, 1),
            entry("Lances et armes d'hast", "magistuarmory:bronze_guisarme", 2500, 1),
            entry("Lances et armes d'hast", "magistuarmory:iron_ahlspiess", 2800, 1),
            entry("Lances et armes d'hast", "magistuarmory:iron_guisarme", 2800, 1),
            entry("Lances et armes d'hast", "magistuarmory:gold_ahlspiess", 2200, 1),
            entry("Lances et armes d'hast", "magistuarmory:gold_guisarme", 2200, 1),
            entry("Lances et armes d'hast", "magistuarmory:silver_ahlspiess", 3000, 1),
            entry("Lances et armes d'hast", "magistuarmory:silver_guisarme", 3000, 1),
            entry("Lances et armes d'hast", "magistuarmory:steel_ahlspiess", 3000, 1),
            entry("Lances et armes d'hast", "magistuarmory:steel_guisarme", 3000, 1),
            entry("Lances et armes d'hast", "magistuarmory:diamond_ahlspiess", 5500, 1),
            entry("Lances et armes d'hast", "magistuarmory:diamond_guisarme", 5500, 1),
            entry("Lances et armes d'hast", "magistuarmory:netherite_ahlspiess", 18000, 1),
            entry("Lances et armes d'hast", "magistuarmory:netherite_guisarme", 18000, 1),

            // ══ Armes à distance (×1) ══ floor 5-40 : 1200-4000 ══
            entry("Armes à distance", "minecraft:bow", 1500, 1),
            entry("Armes à distance", "minecraft:crossbow", 1500, 1),
            entry("Armes à distance", "minecraft:spectral_arrow", 1200, 1),
            entry("Armes à distance", "iceandfire:dragonbone_bow", 3000, 1),
            entry("Armes à distance", "iceandfire:dragonbone_arrow", 3000, 1),
            entry("Armes à distance", "iceandfire:amphithere_arrow", 1500, 1),
            entry("Armes à distance", "iceandfire:hydra_arrow", 1500, 1),
            entry("Armes à distance", "iceandfire:sea_serpent_arrow", 1500, 1),
            entry("Armes à distance", "iceandfire:stymphalian_arrow", 1500, 1),
            entry("Armes à distance", "irons_spellbooks:autoloader_crossbow", 2000, 1),
            entry("Armes à distance", "irons_spellbooks:autoloader_crossbow_arrow", 1200, 1),
            entry("Armes à distance", "magistuarmory:heavy_crossbow", 2000, 1),
            entry("Armes à distance", "magistuarmory:heavy_crossbow_arrow", 1200, 1),
            entry("Armes à distance", "overgeared:iron_arrow", 1500, 1),
            entry("Armes à distance", "overgeared:steel_arrow", 2000, 1),
            entry("Armes à distance", "overgeared:diamond_arrow", 3000, 1),
            entry("Armes à distance", "overgeared:lingering_arrow", 1500, 1),
            entry("Armes à distance", "tensura:ant_crossbow", 2000, 1),
            entry("Armes à distance", "tensura:ant_crossbow_arrow", 1500, 1),

            // ══ Armes de Tensura (×1) ══ floor 15-60 : 3000-22000 ══
            entry("Armes de Tensura", "tensura:silver_short_sword", 3000, 1),
            entry("Armes de Tensura", "tensura:silver_long_sword", 3500, 1),
            entry("Armes de Tensura", "tensura:silver_great_sword", 4000, 1),
            entry("Armes de Tensura", "tensura:silver_katana", 3500, 1),
            entry("Armes de Tensura", "tensura:silver_dagger", 2500, 1),
            entry("Armes de Tensura", "tensura:silver_glaive", 3500, 1),
            entry("Armes de Tensura", "tensura:silver_spear", 3500, 1),
            entry("Armes de Tensura", "tensura:low_magisteel_short_sword", 5000, 1),
            entry("Armes de Tensura", "tensura:low_magisteel_long_sword", 5500, 1),
            entry("Armes de Tensura", "tensura:low_magisteel_great_sword", 6000, 1),
            entry("Armes de Tensura", "tensura:low_magisteel_katana", 5500, 1),
            entry("Armes de Tensura", "tensura:low_magisteel_spear", 5500, 1),
            entry("Armes de Tensura", "tensura:high_magisteel_short_sword", 8000, 1),
            entry("Armes de Tensura", "tensura:high_magisteel_long_sword", 9000, 1),
            entry("Armes de Tensura", "tensura:high_magisteel_great_sword", 10000, 1),
            entry("Armes de Tensura", "tensura:high_magisteel_katana", 9000, 1),
            entry("Armes de Tensura", "tensura:high_magisteel_spear", 9000, 1),
            entry("Armes de Tensura", "tensura:high_magisteel_glaive", 9000, 1),
            entry("Armes de Tensura", "tensura:pure_magisteel_short_sword", 12000, 1),
            entry("Armes de Tensura", "tensura:pure_magisteel_long_sword", 14000, 1),
            entry("Armes de Tensura", "tensura:pure_magisteel_great_sword", 16000, 1),
            entry("Armes de Tensura", "tensura:pure_magisteel_katana", 14000, 1),
            entry("Armes de Tensura", "tensura:pure_magisteel_glaive", 14000, 1),
            entry("Armes de Tensura", "tensura:pure_magisteel_spear", 14000, 1),
            entry("Armes de Tensura", "tensura:hihiirokane_short_sword", 15000, 1),
            entry("Armes de Tensura", "tensura:hihiirokane_long_sword", 18000, 1),
            entry("Armes de Tensura", "tensura:hihiirokane_great_sword", 20000, 1),
            entry("Armes de Tensura", "tensura:hihiirokane_katana", 18000, 1),
            entry("Armes de Tensura", "tensura:adamantite_short_sword", 12000, 1),
            entry("Armes de Tensura", "tensura:adamantite_long_sword", 14000, 1),
            entry("Armes de Tensura", "tensura:adamantite_great_sword", 16000, 1),
            entry("Armes de Tensura", "tensura:adamantite_katana", 14000, 1),
            entry("Armes de Tensura", "tensura:adamantite_dagger", 10000, 1),

            // ══ Armes uniques et légendaires (×1) ══ floor 30+ : 8000-30000 ══
            entry("Armes uniques et légendaires", "simplyswords:runic_katana", 12000, 1),
            entry("Armes uniques et légendaires", "simplyswords:runic_longsword", 12000, 1),
            entry("Armes uniques et légendaires", "simplyswords:runic_claymore", 14000, 1),
            entry("Armes uniques et légendaires", "simplyswords:runic_greataxe", 14000, 1),
            entry("Armes uniques et légendaires", "simplyswords:runic_greathammer", 15000, 1),
            entry("Armes uniques et légendaires", "simplyswords:runic_scythe", 12000, 1),
            entry("Armes uniques et légendaires", "simplyswords:runic_rapier", 10000, 1),
            entry("Armes uniques et légendaires", "simplyswords:runic_cutlass", 10000, 1),
            entry("Armes uniques et légendaires", "simplyswords:runic_sai", 10000, 1),
            entry("Armes uniques et légendaires", "simplyswords:runic_warglaive", 12000, 1),
            entry("Armes uniques et légendaires", "simplyswords:soulkeeper", 12000, 1),
            entry("Armes uniques et légendaires", "simplyswords:twisted_blade", 12000, 1),
            entry("Armes uniques et légendaires", "simplyswords:soulrender", 12000, 1),
            entry("Armes uniques et légendaires", "simplyswords:soulstealer", 12000, 1),
            entry("Armes uniques et légendaires", "simplyswords:stormbringer", 15000, 1),
            entry("Armes uniques et légendaires", "simplyswords:hearthflame", 15000, 1),
            entry("Armes uniques et légendaires", "simplyswords:soulpyre", 15000, 1),
            entry("Armes uniques et légendaires", "simplyswords:mirrorguard", 12000, 1),
            entry("Armes uniques et légendaires", "simplyswords:watching_mirrorguard", 12000, 1),
            entry("Armes uniques et légendaires", "simplyswords:wildvine", 12000, 1),
            entry("Armes uniques et légendaires", "simplyswords:bloomsoul", 12000, 1),
            entry("Armes uniques et légendaires", "iceandfire:dragonsteel_fire_sword", 15000, 1),
            entry("Armes uniques et légendaires", "iceandfire:dragonsteel_ice_sword", 15000, 1),
            entry("Armes uniques et légendaires", "iceandfire:dragonsteel_lightning_sword", 15000, 1),
            entry("Armes uniques et légendaires", "iceandfire:dread_sword", 12000, 1),
            entry("Armes uniques et légendaires", "iceandfire:tide_trident", 12000, 1),
            entry("Armes uniques et légendaires", "iceandfire:ghost_sword", 8000, 1),
            entry("Armes uniques et légendaires", "iceandfire:hippogryph_sword", 8000, 1),
            entry("Armes uniques et légendaires", "tensura:spatial_blade", 25000, 1),
            entry("Armes uniques et légendaires", "tensura:dead_end_rainbow", 30000, 1),
            entry("Armes uniques et légendaires", "tensura:vorpal_sword", 20000, 1),
            entry("Armes uniques et légendaires", "tensura:ice_blade", 20000, 1),
            entry("Armes uniques et légendaires", "tensura:mad_swords", 25000, 1),

            // ══ Armures classiques (×1) ══ floor 5-25 : 800-6000 ══
            entry("Armures classiques", "minecraft:leather_helmet", 800, 1),
            entry("Armures classiques", "minecraft:leather_chestplate", 1000, 1),
            entry("Armures classiques", "minecraft:leather_leggings", 900, 1),
            entry("Armures classiques", "minecraft:leather_boots", 800, 1),
            entry("Armures classiques", "minecraft:chainmail_helmet", 1200, 1),
            entry("Armures classiques", "minecraft:chainmail_chestplate", 1500, 1),
            entry("Armures classiques", "minecraft:chainmail_leggings", 1400, 1),
            entry("Armures classiques", "minecraft:chainmail_boots", 1200, 1),
            entry("Armures classiques", "minecraft:iron_helmet", 1500, 1),
            entry("Armures classiques", "minecraft:iron_chestplate", 2000, 1),
            entry("Armures classiques", "minecraft:iron_leggings", 1800, 1),
            entry("Armures classiques", "minecraft:iron_boots", 1500, 1),
            entry("Armures classiques", "minecraft:golden_helmet", 1800, 1),
            entry("Armures classiques", "minecraft:golden_chestplate", 2200, 1),
            entry("Armures classiques", "minecraft:golden_leggings", 2000, 1),
            entry("Armures classiques", "minecraft:golden_boots", 1800, 1),
            entry("Armures classiques", "minecraft:diamond_helmet", 5000, 1),
            entry("Armures classiques", "minecraft:diamond_chestplate", 6000, 1),
            entry("Armures classiques", "minecraft:diamond_leggings", 5500, 1),
            entry("Armures classiques", "minecraft:diamond_boots", 5000, 1),
            entry("Armures classiques", "minecraft:netherite_helmet", 18000, 1),
            entry("Armures classiques", "minecraft:netherite_chestplate", 22000, 1),
            entry("Armures classiques", "minecraft:netherite_leggings", 20000, 1),
            entry("Armures classiques", "minecraft:netherite_boots", 18000, 1),
            entry("Armures classiques", "overgeared:copper_helmet", 2000, 1),
            entry("Armures classiques", "overgeared:copper_chestplate", 2500, 1),
            entry("Armures classiques", "overgeared:copper_leggings", 2200, 1),
            entry("Armures classiques", "overgeared:copper_boots", 2000, 1),
            entry("Armures classiques", "tensura:silver_helmet", 2500, 1),
            entry("Armures classiques", "tensura:silver_chestplate", 3000, 1),
            entry("Armures classiques", "tensura:silver_leggings", 2800, 1),
            entry("Armures classiques", "tensura:silver_boots", 2500, 1),

            // ══ Armures fantastiques (×1) ══ floor 15-35 : 4000-5000 ══
            entry("Armures fantastiques", "iceandfire:armor_red_helmet", 4000, 1),
            entry("Armures fantastiques", "iceandfire:armor_red_chestplate", 5000, 1),
            entry("Armures fantastiques", "iceandfire:armor_red_leggings", 4500, 1),
            entry("Armures fantastiques", "iceandfire:armor_red_boots", 4000, 1),
            entry("Armures fantastiques", "iceandfire:armor_blue_helmet", 4000, 1),
            entry("Armures fantastiques", "iceandfire:armor_blue_chestplate", 5000, 1),
            entry("Armures fantastiques", "iceandfire:armor_blue_leggings", 4500, 1),
            entry("Armures fantastiques", "iceandfire:armor_blue_boots", 4000, 1),
            entry("Armures fantastiques", "iceandfire:armor_bronze_helmet", 3800, 1),
            entry("Armures fantastiques", "iceandfire:armor_bronze_chestplate", 4800, 1),
            entry("Armures fantastiques", "iceandfire:armor_bronze_leggings", 4300, 1),
            entry("Armures fantastiques", "iceandfire:armor_bronze_boots", 3800, 1),
            entry("Armures fantastiques", "iceandfire:armor_green_helmet", 4000, 1),
            entry("Armures fantastiques", "iceandfire:armor_green_chestplate", 5000, 1),
            entry("Armures fantastiques", "iceandfire:armor_green_leggings", 4500, 1),
            entry("Armures fantastiques", "iceandfire:armor_green_boots", 4000, 1),
            entry("Armures fantastiques", "iceandfire:armor_black_helmet", 3800, 1),
            entry("Armures fantastiques", "iceandfire:armor_black_chestplate", 4800, 1),
            entry("Armures fantastiques", "iceandfire:armor_black_leggings", 4300, 1),
            entry("Armures fantastiques", "iceandfire:armor_black_boots", 3800, 1),
            entry("Armures fantastiques", "iceandfire:armor_gray_helmet", 3600, 1),
            entry("Armures fantastiques", "iceandfire:armor_gray_chestplate", 4600, 1),
            entry("Armures fantastiques", "iceandfire:armor_gray_leggings", 4100, 1),
            entry("Armures fantastiques", "iceandfire:armor_gray_boots", 3600, 1),
            entry("Armures fantastiques", "iceandfire:armor_amethyst_helmet", 4200, 1),
            entry("Armures fantastiques", "iceandfire:armor_amethyst_chestplate", 5200, 1),
            entry("Armures fantastiques", "iceandfire:armor_amethyst_leggings", 4700, 1),
            entry("Armures fantastiques", "iceandfire:armor_amethyst_boots", 4200, 1),
            entry("Armures fantastiques", "iceandfire:armor_sapphire_helmet", 4200, 1),
            entry("Armures fantastiques", "iceandfire:armor_sapphire_chestplate", 5200, 1),
            entry("Armures fantastiques", "iceandfire:armor_sapphire_leggings", 4700, 1),
            entry("Armures fantastiques", "iceandfire:armor_sapphire_boots", 4200, 1),
            entry("Armures fantastiques", "iceandfire:armor_electric_helmet", 4500, 1),
            entry("Armures fantastiques", "iceandfire:armor_electric_chestplate", 5500, 1),
            entry("Armures fantastiques", "iceandfire:armor_electric_leggings", 5000, 1),
            entry("Armures fantastiques", "iceandfire:armor_electric_boots", 4500, 1),

            // ══ Armures historiques (×1) ══ floor 20-50 : 4000-8000 ══
            entry("Armures historiques", "magistuarmory:crusader_helmet", 4000, 1),
            entry("Armures historiques", "magistuarmory:crusader_chestplate", 5000, 1),
            entry("Armures historiques", "magistuarmory:crusader_leggings", 4500, 1),
            entry("Armures historiques", "magistuarmory:crusader_boots", 4000, 1),
            entry("Armures historiques", "magistuarmory:gothic_helmet", 5000, 1),
            entry("Armures historiques", "magistuarmory:gothic_chestplate", 6000, 1),
            entry("Armures historiques", "magistuarmory:gothic_leggings", 5500, 1),
            entry("Armures historiques", "magistuarmory:gothic_boots", 5000, 1),
            entry("Armures historiques", "magistuarmory:maximilian_helmet", 6000, 1),
            entry("Armures historiques", "magistuarmory:maximilian_chestplate", 8000, 1),
            entry("Armures historiques", "magistuarmory:maximilian_leggings", 7000, 1),
            entry("Armures historiques", "magistuarmory:maximilian_boots", 6000, 1),

            // ══ Armures magiques (×1) ══ floor 20-50 : 4000-12000 ══
            entry("Armures magiques", "irons_spellbooks:priest_helmet", 4000, 1),
            entry("Armures magiques", "irons_spellbooks:priest_chestplate", 5000, 1),
            entry("Armures magiques", "irons_spellbooks:priest_leggings", 4500, 1),
            entry("Armures magiques", "irons_spellbooks:priest_boots", 4000, 1),
            entry("Armures magiques", "irons_spellbooks:pyromancer_helmet", 5000, 1),
            entry("Armures magiques", "irons_spellbooks:pyromancer_chestplate", 6000, 1),
            entry("Armures magiques", "irons_spellbooks:pyromancer_leggings", 5500, 1),
            entry("Armures magiques", "irons_spellbooks:pyromancer_boots", 5000, 1),
            entry("Armures magiques", "irons_spellbooks:cryomancer_helmet", 5000, 1),
            entry("Armures magiques", "irons_spellbooks:cryomancer_chestplate", 6000, 1),
            entry("Armures magiques", "irons_spellbooks:cryomancer_leggings", 5500, 1),
            entry("Armures magiques", "irons_spellbooks:cryomancer_boots", 5000, 1),
            entry("Armures magiques", "irons_spellbooks:electromancer_helmet", 5000, 1),
            entry("Armures magiques", "irons_spellbooks:electromancer_chestplate", 6000, 1),
            entry("Armures magiques", "irons_spellbooks:electromancer_leggings", 5500, 1),
            entry("Armures magiques", "irons_spellbooks:electromancer_boots", 5000, 1),
            entry("Armures magiques", "irons_spellbooks:netherite_mage_helmet", 10000, 1),
            entry("Armures magiques", "irons_spellbooks:netherite_mage_chestplate", 12000, 1),
            entry("Armures magiques", "irons_spellbooks:netherite_mage_leggings", 11000, 1),
            entry("Armures magiques", "irons_spellbooks:netherite_mage_boots", 10000, 1),
            entry("Armures magiques", "tensura:low_magisteel_helmet", 4000, 1),
            entry("Armures magiques", "tensura:low_magisteel_chestplate", 5000, 1),
            entry("Armures magiques", "tensura:low_magisteel_leggings", 4500, 1),
            entry("Armures magiques", "tensura:low_magisteel_boots", 4000, 1),
            entry("Armures magiques", "tensura:high_magisteel_helmet", 7000, 1),
            entry("Armures magiques", "tensura:high_magisteel_chestplate", 8000, 1),
            entry("Armures magiques", "tensura:high_magisteel_leggings", 7500, 1),
            entry("Armures magiques", "tensura:high_magisteel_boots", 7000, 1),
            entry("Armures magiques", "tensura:pure_magisteel_helmet", 10000, 1),
            entry("Armures magiques", "tensura:pure_magisteel_chestplate", 12000, 1),
            entry("Armures magiques", "tensura:pure_magisteel_leggings", 11000, 1),
            entry("Armures magiques", "tensura:pure_magisteel_boots", 10000, 1),
            entry("Armures magiques", "tensura:hihiirokane_helmet", 12000, 1),
            entry("Armures magiques", "tensura:hihiirokane_chestplate", 14000, 1),
            entry("Armures magiques", "tensura:hihiirokane_leggings", 13000, 1),
            entry("Armures magiques", "tensura:hihiirokane_boots", 12000, 1),
            entry("Armures magiques", "tensura:adamantite_helmet", 10000, 1),
            entry("Armures magiques", "tensura:adamantite_chestplate", 12000, 1),
            entry("Armures magiques", "tensura:adamantite_leggings", 11000, 1),
            entry("Armures magiques", "tensura:adamantite_boots", 10000, 1),

            // ══ Magie et parchemins (×1) ══ floor 10-50 : 2500-12000 ══
            entry("Magie et parchemins", "irons_spellbooks:copper_spell_book", 3000, 1),
            entry("Magie et parchemins", "irons_spellbooks:iron_spell_book", 3000, 1),
            entry("Magie et parchemins", "irons_spellbooks:gold_spell_book", 3000, 1),
            entry("Magie et parchemins", "irons_spellbooks:diamond_spell_book", 6000, 1),
            entry("Magie et parchemins", "irons_spellbooks:netherite_spell_book", 12000, 1),
            entry("Magie et parchemins", "irons_spellbooks:blaze_spell_book", 3000, 1),
            entry("Magie et parchemins", "irons_spellbooks:druidic_spell_book", 3000, 1),
            entry("Magie et parchemins", "irons_spellbooks:evoker_spell_book", 3000, 1),
            entry("Magie et parchemins", "irons_spellbooks:cursed_doll_spell_book", 3000, 1),
            entry("Magie et parchemins", "irons_spellbooks:dragonskin_spell_book", 6000, 1),
            entry("Magie et parchemins", "irons_spellbooks:blood_staff", 3000, 1),
            entry("Magie et parchemins", "irons_spellbooks:dev_staff", 3000, 1),
            entry("Magie et parchemins", "irons_spellbooks:affinity_ring", 3000, 1),
            entry("Magie et parchemins", "irons_spellbooks:affinity_ring_fire", 3000, 1),
            entry("Magie et parchemins", "irons_spellbooks:affinity_ring_ice", 3000, 1),
            entry("Magie et parchemins", "irons_spellbooks:affinity_ring_lightning", 3000, 1),
            entry("Magie et parchemins", "irons_spellbooks:affinity_ring_holy", 3000, 1),
            entry("Magie et parchemins", "irons_spellbooks:affinity_ring_ender", 3000, 1),
            entry("Magie et parchemins", "irons_spellbooks:affinity_ring_blood", 3000, 1),
            entry("Magie et parchemins", "irons_spellbooks:affinity_ring_evocation", 3000, 1),
            entry("Magie et parchemins", "irons_spellbooks:affinity_ring_nature", 3000, 1),
            entry("Magie et parchemins", "irons_spellbooks:affinity_ring_eldritch", 3000, 1),
            entry("Magie et parchemins", "irons_spellbooks:amethyst_resonance_charm", 3000, 1),
            entry("Magie et parchemins", "apotheosis:potion_charm", 3000, 1),
            entry("Magie et parchemins", "epicfight:skillbook", 5000, 1),
            entry("Magie et parchemins", "iceandfire:dread_queen_staff", 3000, 1),
            entry("Magie et parchemins", "iceandfire:lich_staff", 3000, 1),

            // ══ Runes et composants magiques (×1) ══ floor 5-40 : 1000-8000 ══
            entry("Runes et composants magiques", "irons_spellbooks:arcane_rune", 1200, 1),
            entry("Runes et composants magiques", "irons_spellbooks:blank_rune", 1200, 1),
            entry("Runes et composants magiques", "irons_spellbooks:fire_rune", 1200, 1),
            entry("Runes et composants magiques", "irons_spellbooks:ice_rune", 1200, 1),
            entry("Runes et composants magiques", "irons_spellbooks:lightning_rune", 1200, 1),
            entry("Runes et composants magiques", "irons_spellbooks:holy_rune", 1200, 1),
            entry("Runes et composants magiques", "irons_spellbooks:ender_rune", 1200, 1),
            entry("Runes et composants magiques", "irons_spellbooks:blood_rune", 1200, 1),
            entry("Runes et composants magiques", "irons_spellbooks:evocation_rune", 1200, 1),
            entry("Runes et composants magiques", "irons_spellbooks:nature_rune", 1200, 1),
            entry("Runes et composants magiques", "irons_spellbooks:protection_rune", 1200, 1),
            entry("Runes et composants magiques", "irons_spellbooks:cooldown_rune", 1200, 1),
            entry("Runes et composants magiques", "irons_spellbooks:cinderous_soul_rune", 1200, 1),
            entry("Runes et composants magiques", "irons_spellbooks:arcane_anvil", 1200, 1),
            entry("Runes et composants magiques", "irons_spellbooks:arcane_debris", 1200, 1),
            entry("Runes et composants magiques", "irons_spellbooks:arcane_salvage", 1200, 1),
            entry("Runes et composants magiques", "irons_spellbooks:common_ink", 1200, 1),
            entry("Runes et composants magiques", "irons_spellbooks:uncommon_ink", 1200, 1),
            entry("Runes et composants magiques", "irons_spellbooks:rare_ink", 3000, 1),
            entry("Runes et composants magiques", "irons_spellbooks:epic_ink", 3000, 1),
            entry("Runes et composants magiques", "irons_spellbooks:legendary_ink", 8000, 1),
            entry("Runes et composants magiques", "irons_spellbooks:mana_ring", 1500, 1),
            entry("Runes et composants magiques", "irons_spellbooks:mana_upgrade_orb", 1500, 1),
            entry("Runes et composants magiques", "statmod:rune_essence_arcane", 1200, 1),

            // ══ Potions et soins (×4 sauf potions nommées) ══ floor 1-20 : 800-2500 ══
            entry("Potions et soins", "minecraft:potion", 800, 4),
            entry("Potions et soins", "minecraft:splash_potion", 1000, 4),
            entry("Potions et soins", "minecraft:lingering_potion", 1200, 4),
            entry("Potions et soins", "minecraft:golden_apple", 1200, 4),
            entry("Potions et soins", "minecraft:enchanted_golden_apple", 2000, 4),
            entry("Potions et soins", "minecraft:golden_carrot", 800, 4),
            entry("Potions et soins", "iceandfire:ambrosia", 800, 4),
            entry("Potions et soins", "iceandfire:pixie_dust_milky_tea", 800, 4),
            entry("Potions et soins", "irons_spellbooks:casters_tea", 800, 4),
            entry("Potions et soins", "irons_spellbooks:evasion_elixir", 1200, 4),
            entry("Potions et soins", "irons_spellbooks:invisibility_elixir", 1200, 4),
            entry("Potions et soins", "irons_spellbooks:oakskin_elixir", 1200, 4),
            entry("Potions et soins", "irons_spellbooks:greater_evasion_elixir", 2000, 4),
            entry("Potions et soins", "irons_spellbooks:greater_invisibility_elixir", 2000, 4),
            entry("Potions et soins", "irons_spellbooks:greater_oakskin_elixir", 2000, 4),
            entry("Potions et soins", "tensura:revival_elixir", 2500, 4),
            item("Potions et soins", "minecraft:potion", 1500, 1, "strong_healing"),
            item("Potions et soins", "minecraft:potion", 2000, 1, "strong_strength"),

            // ══ Composants de monstres (×2) ══ floor 10-40 : 1500-5000 ══
            entry("Composants de monstres", "iceandfire:fire_dragon_blood", 4000, 2),
            entry("Composants de monstres", "iceandfire:ice_dragon_blood", 4000, 2),
            entry("Composants de monstres", "iceandfire:lightning_dragon_blood", 4000, 2),
            entry("Composants de monstres", "iceandfire:dragon_horn", 4000, 2),
            entry("Composants de monstres", "iceandfire:hydra_fang", 2000, 2),
            entry("Composants de monstres", "iceandfire:sea_serpent_fang", 2000, 2),
            entry("Composants de monstres", "iceandfire:shiny_scales", 1500, 2),
            entry("Composants de monstres", "iceandfire:amphithere_feather", 1500, 2),
            entry("Composants de monstres", "iceandfire:stymphalian_bird_feather", 1500, 2),
            entry("Composants de monstres", "iceandfire:amphithere_skull", 1500, 2),
            entry("Composants de monstres", "iceandfire:cockatrice_skull", 1500, 2),
            entry("Composants de monstres", "iceandfire:cyclops_skull", 1500, 2),
            entry("Composants de monstres", "iceandfire:hippogryph_skull", 1500, 2),
            entry("Composants de monstres", "iceandfire:hydra_skull", 2000, 2),
            entry("Composants de monstres", "iceandfire:seaserpent_skull", 2000, 2),
            entry("Composants de monstres", "iceandfire:stymphalian_skull", 1500, 2),
            entry("Composants de monstres", "iceandfire:troll_skull", 1500, 2),
            entry("Composants de monstres", "irons_spellbooks:frozen_bone", 1500, 2),
            entry("Composants de monstres", "irons_spellbooks:icy_fang", 1500, 2),
            entry("Composants de monstres", "irons_spellbooks:scroll_blood", 1500, 2),
            entry("Composants de monstres", "mutantmonsters:chemical_x", 2000, 2),
            entry("Composants de monstres", "mutantmonsters:endersoul_hand", 2000, 2),
            entry("Composants de monstres", "mutantmonsters:mutant_skeleton_rib", 2000, 2),
            entry("Composants de monstres", "mutantmonsters:mutant_skeleton_skull", 2000, 2),

            // ══ Nourriture (×8) ══ floor 1-5 : 200-1500 ══
            entry("Nourriture", "farmersdelight:minced_beef", 200, 8),
            entry("Nourriture", "farmersdelight:beef_stew", 200, 8),
            entry("Nourriture", "farmersdelight:chicken_soup", 200, 8),
            entry("Nourriture", "farmersdelight:fish_stew", 200, 8),
            entry("Nourriture", "farmersdelight:noodle_soup", 200, 8),
            entry("Nourriture", "farmersdelight:onion_soup", 200, 8),
            entry("Nourriture", "farmersdelight:pumpkin_soup", 200, 8),
            entry("Nourriture", "farmersdelight:vegetable_soup", 200, 8),
            entry("Nourriture", "farmersdelight:baked_cod_stew", 200, 8),
            entry("Nourriture", "farmersdelight:apple_pie", 200, 8),
            entry("Nourriture", "farmersdelight:chocolate_pie", 200, 8),
            entry("Nourriture", "farmersdelight:roast_chicken", 200, 8),
            entry("Nourriture", "farmersdelight:shepherds_pie", 200, 8),
            entry("Nourriture", "iceandfire:cooked_rice_with_fire_dragon_meat", 1500, 8),
            entry("Nourriture", "iceandfire:cooked_rice_with_ice_dragon_meat", 1500, 8),

            // ══ Fleurs, plantes et bois (×16) ══ floor 1-20 : 200-800 ══
            entry("Fleurs, plantes et bois", "minecraft:oak_sapling", 200, 16),
            entry("Fleurs, plantes et bois", "minecraft:spruce_sapling", 200, 16),
            entry("Fleurs, plantes et bois", "minecraft:birch_sapling", 200, 16),
            entry("Fleurs, plantes et bois", "minecraft:jungle_sapling", 200, 16),
            entry("Fleurs, plantes et bois", "minecraft:acacia_sapling", 200, 16),
            entry("Fleurs, plantes et bois", "minecraft:dark_oak_sapling", 200, 16),
            entry("Fleurs, plantes et bois", "minecraft:cherry_sapling", 400, 16),
            entry("Fleurs, plantes et bois", "minecraft:mangrove_propagule", 400, 16),
            entry("Fleurs, plantes et bois", "minecraft:oak_log", 300, 16),
            entry("Fleurs, plantes et bois", "minecraft:spruce_log", 300, 16),
            entry("Fleurs, plantes et bois", "minecraft:birch_log", 300, 16),
            entry("Fleurs, plantes et bois", "minecraft:jungle_log", 300, 16),
            entry("Fleurs, plantes et bois", "minecraft:acacia_log", 300, 16),
            entry("Fleurs, plantes et bois", "minecraft:dark_oak_log", 300, 16),
            entry("Fleurs, plantes et bois", "minecraft:cherry_log", 500, 16),
            entry("Fleurs, plantes et bois", "minecraft:mangrove_log", 300, 16),
            entry("Fleurs, plantes et bois", "minecraft:oak_planks", 200, 16),
            entry("Fleurs, plantes et bois", "minecraft:spruce_planks", 200, 16),
            entry("Fleurs, plantes et bois", "minecraft:birch_planks", 200, 16),
            entry("Fleurs, plantes et bois", "minecraft:jungle_planks", 200, 16),
            entry("Fleurs, plantes et bois", "minecraft:acacia_planks", 200, 16),
            entry("Fleurs, plantes et bois", "minecraft:dark_oak_planks", 200, 16),
            entry("Fleurs, plantes et bois", "minecraft:cherry_planks", 300, 16),
            entry("Fleurs, plantes et bois", "minecraft:mangrove_planks", 200, 16),
            entry("Fleurs, plantes et bois", "minecraft:wheat_seeds", 200, 16),
            entry("Fleurs, plantes et bois", "minecraft:beetroot_seeds", 200, 16),
            entry("Fleurs, plantes et bois", "minecraft:pumpkin_seeds", 200, 16),
            entry("Fleurs, plantes et bois", "minecraft:melon_seeds", 200, 16),
            entry("Fleurs, plantes et bois", "minecraft:sugar_cane", 300, 16),
            entry("Fleurs, plantes et bois", "minecraft:cactus", 300, 16),
            entry("Fleurs, plantes et bois", "minecraft:bamboo", 300, 16),
            entry("Fleurs, plantes et bois", "minecraft:bone_meal", 300, 16),
            entry("Fleurs, plantes et bois", "minecraft:poppy", 200, 16),
            entry("Fleurs, plantes et bois", "minecraft:dandelion", 200, 16),
            entry("Fleurs, plantes et bois", "minecraft:oxeye_daisy", 200, 16),
            entry("Fleurs, plantes et bois", "minecraft:cornflower", 200, 16),
            entry("Fleurs, plantes et bois", "minecraft:lily_of_the_valley", 200, 16),
            entry("Fleurs, plantes et bois", "minecraft:wither_rose", 800, 16),

            // ══ Construction (×16) ══ floor 5-60 : 400-8000 ══
            entry("Construction", "minecraft:stone", 300, 16),
            entry("Construction", "minecraft:cobblestone", 200, 16),
            entry("Construction", "minecraft:stone_bricks", 400, 16),
            entry("Construction", "minecraft:bricks", 400, 16),
            entry("Construction", "minecraft:glass", 400, 16),
            entry("Construction", "minecraft:glass_pane", 300, 16),
            entry("Construction", "minecraft:sand", 200, 16),
            entry("Construction", "minecraft:gravel", 200, 16),
            entry("Construction", "minecraft:obsidian", 800, 16),
            entry("Construction", "minecraft:crying_obsidian", 1200, 16),
            entry("Construction", "iceandfire:chared_stone", 400, 16),
            entry("Construction", "iceandfire:crackled_stone", 400, 16),
            entry("Construction", "iceandfire:frozen_stone", 400, 16),
            entry("Construction", "iceandfire:dread_stone", 500, 16),
            entry("Construction", "iceandfire:dread_stone_bricks", 500, 16),
            entry("Construction", "iceandfire:dreadwood_planks", 400, 16),
            entry("Construction", "iceandfire:dread_torch", 400, 16),
            entry("Construction", "iceandfire:burnt_torch", 400, 16),
            entry("Construction", "iceandfire:copper_block", 800, 16),
            entry("Construction", "iceandfire:silver_block", 800, 16),
            entry("Construction", "iceandfire:raw_silver_block", 800, 16),
            entry("Construction", "iceandfire:sapphire_block", 1500, 16),
            entry("Construction", "iceandfire:dragon_bone_block", 4000, 16),
            entry("Construction", "iceandfire:dragonsteel_fire_block", 8000, 16),
            entry("Construction", "iceandfire:dragonsteel_ice_block", 8000, 16),
            entry("Construction", "iceandfire:dragonsteel_lightning_block", 8000, 16),
            entry("Construction", "irons_spellbooks:shriving_stone", 600, 16),
            entry("Construction", "irons_spellbooks:wisewood_planks", 400, 16),

            // ══ Mobilité et transport (×1 sauf rails ×8) ══ floor 5-25 : 1200-5000 ══
            entry("Mobilité et transport", "minecraft:saddle", 2500, 1),
            entry("Mobilité et transport", "minecraft:leather_horse_armor", 2000, 1),
            entry("Mobilité et transport", "minecraft:iron_horse_armor", 3000, 1),
            entry("Mobilité et transport", "minecraft:golden_horse_armor", 3500, 1),
            entry("Mobilité et transport", "minecraft:diamond_horse_armor", 5000, 1),
            entry("Mobilité et transport", "minecraft:name_tag", 1500, 1),
            entry("Mobilité et transport", "minecraft:lead", 1200, 1),
            entry("Mobilité et transport", "minecraft:oak_boat", 1200, 1),
            entry("Mobilité et transport", "minecraft:spruce_boat", 1200, 1),
            entry("Mobilité et transport", "minecraft:birch_boat", 1200, 1),
            entry("Mobilité et transport", "minecraft:jungle_boat", 1200, 1),
            entry("Mobilité et transport", "minecraft:acacia_boat", 1200, 1),
            entry("Mobilité et transport", "minecraft:dark_oak_boat", 1200, 1),
            entry("Mobilité et transport", "minecraft:cherry_boat", 1500, 1),
            entry("Mobilité et transport", "minecraft:mangrove_boat", 1200, 1),
            entry("Mobilité et transport", "minecraft:minecart", 1500, 1),
            entry("Mobilité et transport", "minecraft:chest_minecart", 2000, 1),
            entry("Mobilité et transport", "minecraft:hopper_minecart", 2500, 1),
            entry("Mobilité et transport", "minecraft:furnace_minecart", 2000, 1),
            entry("Mobilité et transport", "minecraft:tnt_minecart", 2500, 1),
            entry("Mobilité et transport", "minecraft:rail", 1200, 8),
            entry("Mobilité et transport", "minecraft:powered_rail", 1500, 8),
            entry("Mobilité et transport", "minecraft:detector_rail", 1200, 8),
            entry("Mobilité et transport", "minecraft:activator_rail", 1200, 8),

            // ══ Trophées et décoration (×1) ══ floor 10-40 : 1000-8000 ══
            entry("Trophées et décoration", "minecraft:item_frame", 1000, 1),
            entry("Trophées et décoration", "minecraft:glow_item_frame", 1500, 1),
            entry("Trophées et décoration", "minecraft:painting", 1000, 1),
            entry("Trophées et décoration", "minecraft:armor_stand", 1200, 1),
            entry("Trophées et décoration", "minecraft:flower_pot", 800, 1),
            entry("Trophées et décoration", "minecraft:bell", 1500, 1),
            entry("Trophées et décoration", "minecraft:skeleton_skull", 2000, 1),
            entry("Trophées et décoration", "minecraft:wither_skeleton_skull", 4000, 1),
            entry("Trophées et décoration", "minecraft:zombie_head", 2000, 1),
            entry("Trophées et décoration", "minecraft:creeper_head", 2500, 1),
            entry("Trophées et décoration", "minecraft:dragon_head", 8000, 1),
            entry("Trophées et décoration", "minecraft:piglin_head", 2500, 1),
            entry("Trophées et décoration", "minecraft:end_rod", 1000, 1),
            entry("Trophées et décoration", "minecraft:sea_lantern", 1200, 1),
            entry("Trophées et décoration", "minecraft:shroomlight", 1200, 1),
            entry("Trophées et décoration", "minecraft:bookshelf", 1200, 1),
            entry("Trophées et décoration", "minecraft:chiseled_bookshelf", 1500, 1),
            entry("Trophées et décoration", "minecraft:lectern", 1500, 1),
            entry("Trophées et décoration", "minecraft:spore_blossom", 800, 1),
            entry("Trophées et décoration", "minecraft:glow_berries", 600, 1),
            entry("Trophées et décoration", "minecraft:amethyst_cluster", 1000, 1),

            // ══ Mécanismes et Redstone (×8) ══ floor 5-30 : 500-2000 ══
            entry("Mécanismes et Redstone", "minecraft:piston", 800, 8),
            entry("Mécanismes et Redstone", "minecraft:sticky_piston", 1000, 8),
            entry("Mécanismes et Redstone", "minecraft:observer", 800, 8),
            entry("Mécanismes et Redstone", "minecraft:comparator", 600, 8),
            entry("Mécanismes et Redstone", "minecraft:repeater", 600, 8),
            entry("Mécanismes et Redstone", "minecraft:hopper", 1000, 8),
            entry("Mécanismes et Redstone", "minecraft:dropper", 600, 8),
            entry("Mécanismes et Redstone", "minecraft:dispenser", 800, 8),
            entry("Mécanismes et Redstone", "minecraft:redstone_lamp", 800, 8),
            entry("Mécanismes et Redstone", "minecraft:redstone_torch", 500, 8),
            entry("Mécanismes et Redstone", "minecraft:lever", 500, 8),
            entry("Mécanismes et Redstone", "minecraft:stone_button", 500, 8),
            entry("Mécanismes et Redstone", "minecraft:stone_pressure_plate", 500, 8),
            entry("Mécanismes et Redstone", "minecraft:daylight_detector", 1000, 8),
            entry("Mécanismes et Redstone", "minecraft:target", 600, 8),
            entry("Mécanismes et Redstone", "minecraft:note_block", 600, 8),
            entry("Mécanismes et Redstone", "minecraft:slime_block", 1000, 8),
            entry("Mécanismes et Redstone", "minecraft:honey_block", 1000, 8),
            entry("Mécanismes et Redstone", "minecraft:crafter", 1200, 8),
            entry("Mécanismes et Redstone", "minecraft:lightning_rod", 800, 8),
            entry("Mécanismes et Redstone", "minecraft:sculk_sensor", 1500, 8),
            entry("Mécanismes et Redstone", "minecraft:calibrated_sculk_sensor", 2000, 8),

            // ══ Utilitaires (×1) ══ floor 5-40 : 1200-3000 ══
            entry("Utilitaires", "apotheosis:ender_lead", 1500, 1),
            entry("Utilitaires", "apotheosis:simple_reforging_table", 1500, 1),
            entry("Utilitaires", "apotheosis:reforging_table", 3000, 1),
            entry("Utilitaires", "apotheosis:salvaging_table", 2000, 1),
            entry("Utilitaires", "apotheosis:augmenting_table", 2000, 1),
            entry("Utilitaires", "apotheosis:gem_cutting_table", 2000, 1),
            entry("Utilitaires", "epicfight:glove", 2500, 1),
            entry("Utilitaires", "farmersdelight:rice_bag", 1200, 1),
            entry("Utilitaires", "irons_spellbooks:wayward_compass", 1500, 1),
            entry("Utilitaires", "irons_spellbooks:alchemist_cauldron", 1500, 1),
            entry("Utilitaires", "irons_spellbooks:inscription_table", 2000, 1),
            entry("Utilitaires", "magistuarmory:medieval_bag", 1200, 1),
            entry("Utilitaires", "overgeared:stone_anvil", 1200, 1),
            entry("Utilitaires", "overgeared:drafting_table", 1500, 1),
            entry("Utilitaires", "overgeared:tier_b_smithing_anvil", 1500, 1),
            entry("Utilitaires", "overgeared:casting_furnace", 2000, 1),
            entry("Utilitaires", "overgeared:alloy_furnace", 2000, 1),
            entry("Utilitaires", "overgeared:smithing_anvil", 2000, 1),
            entry("Utilitaires", "overgeared:tier_a_smithing_anvil", 2000, 1),
            entry("Utilitaires", "overgeared:nether_alloy_furnace", 3000, 1),
            entry("Utilitaires", "minecraft:compass", 1200, 1),
            entry("Utilitaires", "minecraft:recovery_compass", 2000, 1),
            entry("Utilitaires", "minecraft:spyglass", 1200, 1),

            // ══ Objets rares contrôlés (×1) ══ floor 50+ : 10000-30000 ══
            entry("Objets rares contrôlés", "apotheosis:gem", 10000, 1),
            entry("Objets rares contrôlés", "apotheosis:gems/blood", 12000, 1),
            entry("Objets rares contrôlés", "apotheosis:gems/cast_time", 10000, 1),
            entry("Objets rares contrôlés", "apotheosis:gems/cooldown", 10000, 1),
            entry("Objets rares contrôlés", "apotheosis:gems/core/ballast", 12000, 1),
            entry("Objets rares contrôlés", "apotheosis:gems/core/bloody_pearl", 12000, 1),
            entry("Objets rares contrôlés", "apotheosis:gems/core/brawlers", 12000, 1),
            entry("Objets rares contrôlés", "apotheosis:gems/core/breach", 12000, 1),
            entry("Objets rares contrôlés", "apotheosis:gems/core/celsius_tear", 15000, 1),
            entry("Objets rares contrôlés", "apotheosis:gems/core/charged_lodestone", 12000, 1),
            entry("Objets rares contrôlés", "apotheosis:gems/core/combatant", 12000, 1),
            entry("Objets rares contrôlés", "apotheosis:gems/core/dragonfire_spessartite", 30000, 1),
            entry("Objets rares contrôlés", "apotheosis:gems/core/effervescent_brimstone", 15000, 1),
            entry("Objets rares contrôlés", "apotheosis:gems/core/golems_onyx", 12000, 1),
            entry("Objets rares contrôlés", "apotheosis:gems/core/guardian", 12000, 1),
            entry("Objets rares contrôlés", "apotheosis:gems/core/lightning", 12000, 1),
            entry("Objets rares contrôlés", "apotheosis:gems/core/luminous_opal", 15000, 1),
            entry("Objets rares contrôlés", "apotheosis:gems/core/lunar", 12000, 1)
        );
    }

    private static SDMShopCatalog.ShopItem entry(String tab, String item, int price, int count) {
        return new SDMShopCatalog.ShopItem(tab, item, price, count, null);
    }

    private static SDMShopCatalog.ShopItem item(String tab, String item, int price, int count, String potionId) {
        return new SDMShopCatalog.ShopItem(tab, item, price, count, potionId);
    }
}
