package tong.statmod.mixin;

import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.crafting.CraftingRecipe;
import net.minecraft.world.item.crafting.RecipeHolder;
import net.minecraft.world.item.crafting.RecipeManager;
import net.minecraft.world.item.crafting.RecipeType;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;
import tong.statmod.STATMod;
import tong.statmod.integration.overgeared.AssemblyResultCache;

import java.lang.reflect.Field;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

/**
 * Intercepts RecipeManager#apply to remove vanilla crafting recipes for items
 * that have a custom Assembly recipe (statmod:assembly/ namespace), preventing
 * duplicates in the crafting grid.
 *
 * NOTE: We intentionally use reflection instead of @Shadow to access the private
 * 'recipes' and 'byName' fields.  @Shadow requires a refmap file generated by the
 * Mixin annotation processor; without it Mixin fails to locate the field and the
 * game crashes with "No refMap loaded". Reflection resolves the field at runtime
 * using known SRG/Mojmap names, making it refmap-independent.
 */
@Mixin(RecipeManager.class)
public class RecipeManagerMixin {

    private static final String ASSEMBLY_PREFIX = "statmod:assembly/";

    // Lazily-resolved reflection references (cached after first successful lookup).
    private static Field FIELD_BY_NAME = null;
    private static Field FIELD_RECIPES = null;

    @Inject(method = "apply(Ljava/util/Map;Lnet/minecraft/server/packs/resources/ResourceManager;Lnet/minecraft/util/profiling/ProfilerFiller;)V",
            at = @At("TAIL"))
    private void statmod$removeNativeRecipes(Map<ResourceLocation, RecipeHolder<?>> map,
                                             net.minecraft.server.packs.resources.ResourceManager resourceManager,
                                             net.minecraft.util.profiling.ProfilerFiller profiler,
                                             CallbackInfo ci) {
        try {
            RecipeManager self = (RecipeManager) (Object) this;

            Map<ResourceLocation, RecipeHolder<?>> byName = getByName(self);
            Map<RecipeType<?>, Map<ResourceLocation, RecipeHolder<?>>> recipes = getRecipes(self);

            if (byName == null || recipes == null) {
                STATMod.LOGGER.warn("RecipeManagerMixin: could not access RecipeManager fields via reflection, skipping assembly suppression");
                return;
            }

            // Collect all result item IDs from assembly recipes.
            Set<ResourceLocation> assemblyResults = new HashSet<>();
            for (Map.Entry<ResourceLocation, RecipeHolder<?>> entry : byName.entrySet()) {
                if (!entry.getKey().toString().startsWith(ASSEMBLY_PREFIX)) continue;
                ResourceLocation itemId = extractResultId(entry.getValue());
                if (itemId != null) {
                    assemblyResults.add(itemId);
                }
            }

            AssemblyResultCache.rebuild(assemblyResults);

            if (assemblyResults.isEmpty()) return;

            // Collect vanilla recipes that produce the same output as an assembly recipe.
            Set<ResourceLocation> toRemove = new HashSet<>();
            for (Map.Entry<ResourceLocation, RecipeHolder<?>> entry : byName.entrySet()) {
                ResourceLocation id = entry.getKey();
                if (id.toString().startsWith(ASSEMBLY_PREFIX)) continue;
                ResourceLocation resultId = extractResultId(entry.getValue());
                if (resultId != null && assemblyResults.contains(resultId)) {
                    toRemove.add(id);
                }
            }

            int removed = 0;
            for (ResourceLocation id : toRemove) {
                byName.remove(id);
                for (Map<ResourceLocation, RecipeHolder<?>> typeMap : recipes.values()) {
                    typeMap.remove(id);
                }
                removed++;
            }

            if (removed > 0) {
                STATMod.LOGGER.debug("RecipeManagerMixin: suppressed {} native recipe(s) for {} assembly item(s)",
                        removed, assemblyResults.size());
            }
        } catch (Exception e) {
            STATMod.LOGGER.error("RecipeManagerMixin: unexpected error during assembly recipe suppression", e);
        }
    }

    // -------------------------------------------------------------------------
    // Reflection helpers
    // -------------------------------------------------------------------------

    @SuppressWarnings("unchecked")
    private static Map<ResourceLocation, RecipeHolder<?>> getByName(RecipeManager manager) {
        if (FIELD_BY_NAME == null) {
            FIELD_BY_NAME = resolveField(RecipeManager.class, "byName", "f_44007_");
        }
        if (FIELD_BY_NAME == null) return null;
        try {
            return (Map<ResourceLocation, RecipeHolder<?>>) FIELD_BY_NAME.get(manager);
        } catch (Exception e) {
            STATMod.LOGGER.error("RecipeManagerMixin: failed to read byName field", e);
            return null;
        }
    }

    @SuppressWarnings("unchecked")
    private static Map<RecipeType<?>, Map<ResourceLocation, RecipeHolder<?>>> getRecipes(RecipeManager manager) {
        if (FIELD_RECIPES == null) {
            FIELD_RECIPES = resolveField(RecipeManager.class, "recipes", "f_44006_");
        }
        if (FIELD_RECIPES == null) return null;
        try {
            return (Map<RecipeType<?>, Map<ResourceLocation, RecipeHolder<?>>>) FIELD_RECIPES.get(manager);
        } catch (Exception e) {
            STATMod.LOGGER.error("RecipeManagerMixin: failed to read recipes field", e);
            return null;
        }
    }

    /**
     * Tries to find a private field by Mojmap name first, then SRG name.
     * Returns null (with a warning) if neither is found.
     */
    private static Field resolveField(Class<?> clazz, String mojmapName, String srgName) {
        for (String name : new String[]{mojmapName, srgName}) {
            try {
                Field f = clazz.getDeclaredField(name);
                f.setAccessible(true);
                STATMod.LOGGER.debug("RecipeManagerMixin: resolved field '{}' as '{}'", mojmapName, name);
                return f;
            } catch (NoSuchFieldException ignored) {}
        }
        // Last resort: scan all declared fields by type signature
        for (Field f : clazz.getDeclaredFields()) {
            if (f.getType() == Map.class) {
                // There are two Map fields; pick by name containing "name" hint
                if (mojmapName.equals("byName") && f.getName().toLowerCase().contains("name")) {
                    f.setAccessible(true);
                    STATMod.LOGGER.debug("RecipeManagerMixin: resolved field '{}' by heuristic as '{}'", mojmapName, f.getName());
                    return f;
                }
            }
        }
        STATMod.LOGGER.warn("RecipeManagerMixin: could not resolve field '{}' (tried mojmap='{}' and srg='{}')",
                mojmapName, mojmapName, srgName);
        return null;
    }

    // -------------------------------------------------------------------------
    // Utility
    // -------------------------------------------------------------------------

    private static ResourceLocation extractResultId(RecipeHolder<?> holder) {
        net.minecraft.world.item.crafting.Recipe<?> recipe = holder.value();
        if (recipe instanceof CraftingRecipe crafting) {
            return BuiltInRegistries.ITEM.getKey(crafting.getResultItem(null).getItem());
        }
        try {
            Object result = recipe.getClass().getMethod("getResultItem", net.minecraft.core.RegistryAccess.class)
                    .invoke(recipe, (Object) null);
            if (result instanceof net.minecraft.world.item.ItemStack stack && !stack.isEmpty()) {
                return BuiltInRegistries.ITEM.getKey(stack.getItem());
            }
        } catch (Exception ignored) {}
        try {
            Object result = recipe.getClass().getMethod("resultItem").invoke(recipe);
            if (result instanceof net.minecraft.world.item.ItemStack stack && !stack.isEmpty()) {
                return BuiltInRegistries.ITEM.getKey(stack.getItem());
            }
        } catch (Exception ignored) {}
        return null;
    }
}
