modLoader="javafml" #mandatory
loaderVersion="[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All RIGHT RESERVED"
issueTrackerURL="https://github.com/Reascer/WeaponsOfMinecraft/issues" #optional
[[mods]] #mandatory
modId="wom" #mandatory
version="2.0.15" #mandatory
displayName="Weapons of miracle" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/weapons-of-miracles-epicfight" #optional
logoFile="wom_logo.png" #optional
credits="Special mention to Asan who started it all... Yesman, METAL, Ellet and all of you who support wom." #optional
authors="Reascer" #optional
description='''Weapons from another reality, waiting for you to find them and witness their powers !'''

[[dependencies.wom]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[47,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.wom]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.wom]]
    modId="epicfight"
    mandatory=true
    versionRange="[20.14.3,)"
    ordering="AFTER"
    side="BOTH"
