package tong.statmod.perks;

public enum AutomaticPerkEffect {
    RAPIDITE_ATTACK_SPEED,
    AGILITY_MOVEMENT,
    ENDURANCE_STAMINA,
    ARCANE_SPELL_POWER,
    CASTING_SPEED_REDUCTIONS,
    MANA_CAPACITY_REGEN,
    MAGIC_RESISTANCE,
    BRUTE_FORCE_DAMAGE,
    BLADE_TECHNIQUE_DAMAGE,
    PRECISION_DAMAGE,
    PHYSICAL_RESISTANCE,
    WILLPOWER_KNOCKBACK_RESISTANCE,
    INTIMIDATION_ARMOR_TOUGHNESS
}
