package tong.statmod.dungeon;

import java.util.List;

/**
 * Mission M6 — 100 thèmes de donjon pour Forge 1.20.1.
 *
 * <p>Basés sur les mods RÉELLEMENT disponibles dans le dossier client test-vrai :
 * slu, irons_spellbooks, epic_mobs, mutantmonsters, mowziesmobs,
 * block_factorys_bosses, deeperdarker, darkdoppelganger, bosses_of_mass_destruction.
 *
 * <p>Mods RETIRÉS (absents en 1.20.1) : tensura, cataclysm, born_in_chaos_v1,
 * alexsmobs, iceandfire.
 */
public final class DungeonThemes {

    public record Theme(String displayName, List<String> adds, List<String> miniBoss) {}

    private DungeonThemes() {}

    private static final Theme[] THEMES = {

        // ═══ ARC 1 (1-10) — LES DÉCHARNÉS (§7, gris) ═══════════════════════
        new Theme("§7Les Décharnés — La Herse Rouillée",
                List.of("minecraft:zombie", "minecraft:skeleton", "slu:hollow"),
                List.of("minecraft:iron_golem")),
        new Theme("§7Les Décharnés — Les Geôles Effondrées",
                List.of("slu:hollow", "slu:armed_hollow", "minecraft:silverfish"),
                List.of("epic_mobs:bronze_guard")),
        new Theme("§7Les Décharnés — L'Armurerie des Morts",
                List.of("slu:thief", "minecraft:husk", "minecraft:zombie_villager"),
                List.of("slu:executor")),
        new Theme("§7Les Décharnés — Le Réfectoire aux Mouches",
                List.of("minecraft:cave_spider", "deeperdarker:sculk_leech", "slu:hollow_soldier_sword"),
                List.of("minecraft:creeper")),
        new Theme("§7Les Décharnés — La Salle de Garde Abandonnée",
                List.of("slu:hollow_soldier_spear", "minecraft:skeleton", "slu:twisted_souls"),
                List.of("minecraft:bogged")),
        new Theme("§7Les Décharnés — Le Puits aux Chaînes",
                List.of("minecraft:zombie_villager", "block_factorys_bosses:frozen_skeleton",
                        "minecraft:skeleton"),
                List.of("slu:thief")),
        new Theme("§7Les Décharnés — La Chapelle des Os",
                List.of("block_factorys_bosses:soul_skeleton", "epic_mobs:bronze_guard",
                        "epic_mobs:bronze_spinner"),
                List.of("slu:armed_hollow")),
        new Theme("§7Les Décharnés — L'Antichambre des Rats",
                List.of("minecraft:slime", "slu:thief", "minecraft:zombie_villager"),
                List.of("minecraft:witch")),
        new Theme("§7Les Décharnés — La Cour aux Supplices",
                List.of("slu:hollow_soldier_sword", "minecraft:husk", "minecraft:zombie"),
                List.of("minecraft:iron_golem")),
        new Theme("§7Les Décharnés — La Porte que Nul ne Garde",
                List.of("slu:armed_hollow", "block_factorys_bosses:flaming_skeleton_guard_sword",
                        "minecraft:bogged"),
                List.of("epic_mobs:infernal_eye")),

        // ═══ ARC 2 (11-20) — LES FAUVES (§2, vert) ══════════════════════════
        new Theme("§2Les Fauves — L'Enclos Éventré",
                List.of("minecraft:wolf", "mowziesmobs:foliaath", "minecraft:wolf"),
                List.of("epic_mobs:frost_knight")),
        new Theme("§2Les Fauves — La Tanière du Prédateur",
                List.of("mowziesmobs:foliaath", "mowziesmobs:umvuthana", "mowziesmobs:umvuthana_raptor"),
                List.of("deeperdarker:stalker")),
        new Theme("§2Les Fauves — Le Terrier des Tisseuses",
                List.of("minecraft:spider", "minecraft:cave_spider", "deeperdarker:sculk_centipede"),
                List.of("mowziesmobs:foliaath")),
        new Theme("§2Les Fauves — La Volière aux Dards",
                List.of("deeperdarker:sculk_centipede", "minecraft:cave_spider", "minecraft:bee"),
                List.of("epic_mobs:frostrogue")),
        new Theme("§2Les Fauves — La Grotte aux Fauves",
                List.of("mowziesmobs:foliaath", "mowziesmobs:umvuthana_raptor", "minecraft:wolf"),
                List.of("mowziesmobs:grottol")),
        new Theme("§2Les Fauves — Le Verger Empoisonné",
                List.of("mowziesmobs:bluff", "minecraft:stray", "deeperdarker:sculk_leech"),
                List.of("epic_mobs:frost_knight")),
        new Theme("§2Les Fauves — La Clairière des Chairs",
                List.of("mowziesmobs:foliaath", "minecraft:wolf", "minecraft:spider"),
                List.of("minecraft:creeper")),
        new Theme("§2Les Fauves — Les Fourrés Mouvants",
                List.of("minecraft:wolf", "mowziesmobs:grottol", "mowziesmobs:umvuthana"),
                List.of("epic_mobs:frostgeneral")),
        new Theme("§2Les Fauves — Le Nid du Silencieux",
                List.of("deeperdarker:sculk_centipede", "deeperdarker:sculk_snapper", "minecraft:cave_spider"),
                List.of("deeperdarker:stalker")),
        new Theme("§2Les Fauves — Le Repaire de l'Alpha",
                List.of("minecraft:wolf", "mowziesmobs:foliaath", "epic_mobs:frost_knight"),
                List.of("epic_mobs:frostgeneral")),

        // ═══ ARC 3 (21-30) — LES TRIBUS (§c, rouge) ═════════════════════════
        new Theme("§cLes Tribus — Le Camp des Éclaireurs",
                List.of("minecraft:pillager", "minecraft:vindicator", "slu:knight"),
                List.of("epic_mobs:frostgeneral")),
        new Theme("§cLes Tribus — La Palissade Hurlante",
                List.of("minecraft:vindicator", "minecraft:pillager", "epic_mobs:frostguard"),
                List.of("minecraft:ravager")),
        new Theme("§cLes Tribus — L'Armurerie des Félons",
                List.of("slu:castle_guard", "slu:hollow_knight", "minecraft:vindicator"),
                List.of("slu:monster_tower_knight")),
        new Theme("§cLes Tribus — Le Chenil de Guerre",
                List.of("minecraft:wolf", "minecraft:zombified_piglin", "mowziesmobs:umvuthana_raptor"),
                List.of("epic_mobs:frostgeneral")),
        new Theme("§cLes Tribus — La Solde du Mercenaire",
                List.of("minecraft:pillager", "minecraft:vindicator", "slu:thief"),
                List.of("minecraft:ravager")),
        new Theme("§cLes Tribus — La Cour des Duels",
                List.of("slu:dungeon_knight", "slu:nightmare_knight", "minecraft:evoker"),
                List.of("slu:knight")),
        new Theme("§cLes Tribus — Les Écuries Brûlées",
                List.of("minecraft:vindicator", "minecraft:zombified_piglin", "minecraft:piglin"),
                List.of("epic_mobs:frost_knight")),
        new Theme("§cLes Tribus — La Tente du Stratège",
                List.of("mowziesmobs:umvuthana_crane", "minecraft:evoker", "slu:castle_guard"),
                List.of("minecraft:vindicator")),
        new Theme("§cLes Tribus — Le Front des Bannières",
                List.of("slu:elite_knight", "mowziesmobs:umvuthana", "minecraft:pillager"),
                List.of("epic_mobs:frostgeneral")),
        new Theme("§cLes Tribus — L'État-Major Renégat",
                List.of("minecraft:ravager", "slu:nightmare_knight", "epic_mobs:frost_knight"),
                List.of("deeperdarker:stalker")),

        // ═══ ARC 4 (31-40) — LA LÉGION NOIRE (§8, gris foncé) ════════════════
        new Theme("§8La Légion Noire — Les Fosses des Damnés",
                List.of("slu:ghost_samurai", "minecraft:wither_skeleton", "slu:dark_spirit"),
                List.of("slu:elite_knight")),
        new Theme("§8La Légion Noire — Le Caveau des Traîtres",
                List.of("slu:dungeon_knight", "slu:noble_knight", "minecraft:vindicator"),
                List.of("deeperdarker:shattered")),
        new Theme("§8La Légion Noire — La Salle des Suaires",
                List.of("epic_mobs:radiant_guard", "minecraft:enderman", "minecraft:evoker"),
                List.of("mutantmonsters:mutant_zombie")),
        new Theme("§8La Légion Noire — Le Pont des Soupirs",
                List.of("slu:elite_knight", "minecraft:creeper", "minecraft:evoker"),
                List.of("slu:ghost_samurai")),
        new Theme("§8La Légion Noire — L'Armurerie Noire",
                List.of("slu:ghost_samurai", "slu:dungeon_knight", "slu:dark_spirit"),
                List.of("minecraft:wither_skeleton")),
        new Theme("§8La Légion Noire — Le Donjon aux Mille Yeux",
                List.of("minecraft:enderman", "minecraft:vex", "minecraft:wither_skeleton"),
                List.of("mutantmonsters:mutant_skeleton")),
        new Theme("§8La Légion Noire — Les Écuries Spectrales",
                List.of("irons_spellbooks:cultist", "slu:elite_knight", "epic_mobs:radiant_smasher"),
                List.of("epic_mobs:radiant_guard")),
        new Theme("§8La Légion Noire — La Crypte des Félons",
                List.of("slu:nightmare_knight", "minecraft:enderman", "slu:elite_knight"),
                List.of("mutantmonsters:mutant_skeleton")),
        new Theme("§8La Légion Noire — La Cour des Ombres",
                List.of("slu:ghost_samurai", "minecraft:wither_skeleton", "slu:wither_skeleton_knight"),
                List.of("deeperdarker:shattered")),
        new Theme("§8La Légion Noire — Le Trône de la Légion",
                List.of("slu:elite_knight", "minecraft:wither_skeleton", "epic_mobs:radiant_smasher"),
                List.of("deeperdarker:stalker")),

        // ═══ ARC 5 (41-50) — LES ABYSSES (§3, cyan) ═══════════════════════════
        new Theme("§3Les Abysses — Le Vestibule des Marées",
                List.of("minecraft:drowned", "minecraft:drowned", "minecraft:elder_guardian"),
                List.of("block_factorys_bosses:pirate_captain")),
        new Theme("§3Les Abysses — Les Jardins de Corail",
                List.of("minecraft:cave_spider", "minecraft:drowned", "minecraft:iron_golem"),
                List.of("block_factorys_bosses:kraken")),
        new Theme("§3Les Abysses — La Cale des Écumeurs",
                List.of("block_factorys_bosses:crossbow_pirate", "block_factorys_bosses:pirate_rook",
                        "minecraft:drowned"),
                List.of("block_factorys_bosses:pirate_captain")),
        new Theme("§3Les Abysses — La Salle de Bal Immergée",
                List.of("minecraft:drowned", "deeperdarker:sludge", "minecraft:guardian"),
                List.of("block_factorys_bosses:pirate_captain")),
        new Theme("§3Les Abysses — Le Trésor de la Frégate",
                List.of("block_factorys_bosses:crossbow_pirate", "minecraft:drowned", "deeperdarker:sludge"),
                List.of("block_factorys_bosses:soul_skeleton")),
        new Theme("§3Les Abysses — L'Aquarium des Monstres",
                List.of("minecraft:guardian", "minecraft:phantom", "minecraft:cave_spider"),
                List.of("block_factorys_bosses:kraken")),
        new Theme("§3Les Abysses — Les Autels de la Vase",
                List.of("deeperdarker:sludge", "epic_mobs:bronze_guard", "minecraft:drowned"),
                List.of("epic_mobs:frostgeneral")),
        new Theme("§3Les Abysses — Le Chœur des Abysses",
                List.of("deeperdarker:sludge", "deeperdarker:sculk_snapper", "minecraft:guardian"),
                List.of("block_factorys_bosses:kraken")),
        new Theme("§3Les Abysses — Le Pont des Amiraux",
                List.of("block_factorys_bosses:pirate_rook", "minecraft:drowned",
                        "block_factorys_bosses:crossbow_pirate"),
                List.of("block_factorys_bosses:underworld_knight")),
        new Theme("§3Les Abysses — La Salle du Trône Englouti",
                List.of("block_factorys_bosses:pirate_captain", "deeperdarker:shattered", "minecraft:drowned"),
                List.of("block_factorys_bosses:underworld_knight")),

        // ═══ ARC 6 (51-60) — LE CERCLE DES MAGES (§d, rose) ══════════════════
        new Theme("§dLe Cercle des Mages — Le Hall des Apprentis",
                List.of("irons_spellbooks:cultist", "minecraft:witch", "epic_mobs:radiant_archer"),
                List.of("irons_spellbooks:archevoker")),
        new Theme("§dLe Cercle des Mages — L'Amphithéâtre des Flammes",
                List.of("irons_spellbooks:pyromancer", "minecraft:blaze", "epic_mobs:infernal_eye"),
                List.of("epic_mobs:phoenix_fight")),
        new Theme("§dLe Cercle des Mages — La Bibliothèque Interdite",
                List.of("irons_spellbooks:catacombs_zombie", "irons_spellbooks:priest", "minecraft:vex"),
                List.of("irons_spellbooks:cryomancer")),
        new Theme("§dLe Cercle des Mages — Le Laboratoire des Golems",
                List.of("irons_spellbooks:magehunter_vindicator", "minecraft:evoker", "epic_mobs:tech_knight"),
                List.of("epic_mobs:the_knight")),
        new Theme("§dLe Cercle des Mages — Le Coffre du Doyen",
                List.of("irons_spellbooks:cryomancer", "minecraft:witch", "irons_spellbooks:apothecarist"),
                List.of("irons_spellbooks:pyromancer")),
        new Theme("§dLe Cercle des Mages — L'Aile des Élémentaires",
                List.of("minecraft:blaze", "minecraft:witch", "minecraft:vex"),
                List.of("epic_mobs:phoenix_fight")),
        new Theme("§dLe Cercle des Mages — Le Givre de la Chaire",
                List.of("irons_spellbooks:cryomancer", "irons_spellbooks:ice_spider", "epic_mobs:frost_knight"),
                List.of("irons_spellbooks:apothecarist")),
        new Theme("§dLe Cercle des Mages — Les Ateliers de Chair",
                List.of("irons_spellbooks:necromancer", "irons_spellbooks:catacombs_zombie",
                        "minecraft:zombie"),
                List.of("irons_spellbooks:magehunter_vindicator")),
        new Theme("§dLe Cercle des Mages — L'Observatoire des Tempêtes",
                List.of("minecraft:vex", "epic_mobs:radiant_archer", "irons_spellbooks:pyromancer"),
                List.of("epic_mobs:tech_knight")),
        new Theme("§dLe Cercle des Mages — La Thèse Finale",
                List.of("irons_spellbooks:archevoker", "irons_spellbooks:necromancer", "epic_mobs:tech_knight"),
                List.of("epic_mobs:the_knight")),

        // ═══ ARC 7 (61-70) — LA MOISSON DE L'EFFROI (§6, or) ════════════════
        new Theme("§6La Moisson de l'Effroi — La Procession des Lanternes",
                List.of("minecraft:witch", "minecraft:vex", "minecraft:zombie_villager"),
                List.of("epic_mobs:micky")),
        new Theme("§6La Moisson de l'Effroi — Le Bal des Épouvantails",
                List.of("minecraft:zombie_villager", "minecraft:witch",
                        "minecraft:phantom"),
                List.of("epic_mobs:pillager_king")),
        new Theme("§6La Moisson de l'Effroi — Les Feux Follets du Verger",
                List.of("minecraft:blaze", "slu:dark_knight", "minecraft:vex"),
                List.of("deeperdarker:stalker")),
        new Theme("§6La Moisson de l'Effroi — Le Pressoir aux Ombres",
                List.of("slu:ringed_knight", "minecraft:witch", "minecraft:vex"),
                List.of("epic_mobs:the_knight")),
        new Theme("§6La Moisson de l'Effroi — Le Grenier du Rémouleur",
                List.of("minecraft:witch", "slu:shadow_assassin", "minecraft:zombie_villager"),
                List.of("slu:monster_successor")),
        new Theme("§6La Moisson de l'Effroi — La Ronde des Masques",
                List.of("slu:ringed_knight", "slu:mad_knight", "minecraft:blaze"),
                List.of("epic_mobs:micky")),
        new Theme("§6La Moisson de l'Effroi — Le Champ des Têtes Sculptées",
                List.of("epic_mobs:bronze_guard", "epic_mobs:bronze_spinner",
                        "minecraft:zombie_villager"),
                List.of("epic_mobs:pillager_king")),
        new Theme("§6La Moisson de l'Effroi — Les Brasiers de la Veillée",
                List.of("minecraft:blaze", "slu:wither_skeleton_knight", "minecraft:vex"),
                List.of("deeperdarker:stalker")),
        new Theme("§6La Moisson de l'Effroi — Le Cortège de Minuit",
                List.of("slu:mad_knight", "slu:shadow_assassin", "minecraft:witch"),
                List.of("slu:monster_successor")),
        new Theme("§6La Moisson de l'Effroi — Le Banquet du Roi-Citrouille",
                List.of("epic_mobs:bronze_guard", "epic_mobs:bronzer",
                        "minecraft:zombie_villager"),
                List.of("epic_mobs:the_knight")),

        // ═══ ARC 8 (71-80) — LA FOURNAISE (§4, rouge foncé) ══════════════════
        new Theme("§4La Fournaise — Les Soufflets Hurlants",
                List.of("minecraft:blaze", "epic_mobs:infernal_eye", "minecraft:magma_cube"),
                List.of("epic_mobs:tech_knight")),
        new Theme("§4La Fournaise — La Chaîne des Enclumes",
                List.of("minecraft:wither_skeleton", "block_factorys_bosses:soul_knight_wither_skeleton",
                        "epic_mobs:infernal_eye"),
                List.of("epic_mobs:tech_knight")),
        new Theme("§4La Fournaise — Le Bassin de Trempe",
                List.of("minecraft:magma_cube", "minecraft:hoglin", "epic_mobs:bronze_guard"),
                List.of("epic_mobs:infernal_eye")),
        new Theme("§4La Fournaise — Les Galeries du Minerai Noir",
                List.of("epic_mobs:infernal_eye", "epic_mobs:hypo_fight",
                        "minecraft:wither_skeleton"),
                List.of("minecraft:hoglin")),
        new Theme("§4La Fournaise — La Paie des Damnés",
                List.of("epic_mobs:hypo_fight", "minecraft:phantom", "minecraft:piglin_brute"),
                List.of("epic_mobs:tech_knight")),
        new Theme("§4La Fournaise — L'Atelier des Armures",
                List.of("epic_mobs:infernal_eye", "minecraft:blaze", "epic_mobs:radiant_smasher"),
                List.of("epic_mobs:hypo_fight")),
        new Theme("§4La Fournaise — Le Tribunal des Braises",
                List.of("epic_mobs:infernal_eye", "epic_mobs:hypo_fight", "minecraft:blaze"),
                List.of("epic_mobs:phoenix_fight")),
        new Theme("§4La Fournaise — La Fonderie des Colosses",
                List.of("minecraft:hoglin", "minecraft:magma_cube", "minecraft:phantom"),
                List.of("minecraft:piglin_brute")),
        new Theme("§4La Fournaise — Le Couloir des Fours Ouverts",
                List.of("epic_mobs:infernal_eye", "minecraft:blaze", "epic_mobs:hypo_fight"),
                List.of("epic_mobs:tech_knight")),
        new Theme("§4La Fournaise — Le Maître des Soufflets",
                List.of("epic_mobs:infernal_eye", "minecraft:blaze", "epic_mobs:hypo_fight"),
                List.of("block_factorys_bosses:infernal_dragon")),

        // ═══ ARC 9 (81-90) — LA GESTE DÉMONIAQUE (§5, violet) ════════════════
        new Theme("§5La Geste Démoniaque — L'Antichambre du Fléau",
                List.of("epic_mobs:radiant_smasher", "slu:elite_knight", "minecraft:vex"),
                List.of("epic_mobs:tech_knight")),
        new Theme("§5La Geste Démoniaque — La Salle des Rituels",
                List.of("epic_mobs:infernal_eye", "slu:elite_knight",
                        "minecraft:evoker"),
                List.of("darkdoppelganger:dark_doppelganger")),
        new Theme("§5La Geste Démoniaque — Le Couloir aux Cent Pattes",
                List.of("deeperdarker:sculk_centipede", "deeperdarker:shriek_worm", "mowziesmobs:umvuthi"),
                List.of("epic_mobs:the_knight")),
        new Theme("§5La Geste Démoniaque — Les Appartements du Non-Mort",
                List.of("slu:knight", "minecraft:evoker", "irons_spellbooks:necromancer"),
                List.of("deeperdarker:stalker")),
        new Theme("§5La Geste Démoniaque — La Salle de la Perdition",
                List.of("epic_mobs:radiant_smasher", "minecraft:pillager",
                        "deeperdarker:shattered"),
                List.of("mutantmonsters:mutant_creeper")),
        new Theme("§5La Geste Démoniaque — Le Jardin des Âmes",
                List.of("epic_mobs:infernal_eye", "epic_mobs:hypo_fight",
                        "slu:elite_knight"),
                List.of("epic_mobs:phoenix_fight")),
        new Theme("§5La Geste Démoniaque — Le Vestibule des Martyrs",
                List.of("epic_mobs:infernal_eye", "mowziesmobs:naga", "deeperdarker:sculk_centipede"),
                List.of("darkdoppelganger:dark_doppelganger")),
        new Theme("§5La Geste Démoniaque — La Fonderie des Supplices",
                List.of("deeperdarker:shriek_worm", "mowziesmobs:naga", "deeperdarker:shattered"),
                List.of("mutantmonsters:mutant_enderman")),
        new Theme("§5La Geste Démoniaque — Le Pont des Âmes Perdues",
                List.of("epic_mobs:hypo_fight", "slu:elite_knight",
                        "epic_mobs:infernal_eye"),
                List.of("epic_mobs:tech_knight")),
        new Theme("§5La Geste Démoniaque — Le Trône du Fléau",
                List.of("epic_mobs:radiant_smasher", "epic_mobs:infernal_eye", "slu:elite_knight"),
                List.of("block_factorys_bosses:infernal_dragon")),

        // ═══ ARC 10 (91-100) — LE TRÔNE DU NÉANT (§5, violet) ════════════════
        new Theme("§5Le Trône du Néant — L'Antichambre du Vide",
                List.of("minecraft:enderman", "minecraft:endermite", "slu:monster_godrick_soldier"),
                List.of("slu:monster_crucible_knight")),
        new Theme("§5Le Trône du Néant — La Galerie des Reflets Faux",
                List.of("slu:white_phantom", "minecraft:shulker", "minecraft:endermite"),
                List.of("slu:monster_successor")),
        new Theme("§5Le Trône du Néant — Le Jardin de Cristal Mort",
                List.of("minecraft:enderman", "minecraft:iron_golem", "minecraft:endermite"),
                List.of("slu:bad_omen_giant")),
        new Theme("§5Le Trône du Néant — Les Marches du Silence",
                List.of("slu:monster_godrick_knight", "slu:clone_abyss_watcher", "minecraft:shulker"),
                List.of("slu:bad_omen_giant")),
        new Theme("§5Le Trône du Néant — Le Reliquaire de la Couronne",
                List.of("slu:monster_crusader", "minecraft:endermite", "minecraft:phantom"),
                List.of("slu:monster_successor")),
        new Theme("§5Le Trône du Néant — La Salle des Souverains Effacés",
                List.of("slu:monster_blasphemy_knight", "slu:temple_guard", "minecraft:enderman"),
                List.of("slu:bad_omen_giant")),
        new Theme("§5Le Trône du Néant — Le Pont au-dessus de Rien",
                List.of("minecraft:phantom", "slu:executor", "slu:white_phantom"),
                List.of("minecraft:iron_golem")),
        new Theme("§5Le Trône du Néant — La Chambre des Échos",
                List.of("slu:monster_crucible_knight", "block_factorys_bosses:dragon_guard_sword",
                        "minecraft:shulker"),
                List.of("mutantmonsters:mutant_enderman")),
        new Theme("§5Le Trône du Néant — L'Ultime Garde",
                List.of("slu:monster_crucible_knight_2", "slu:monster_blasphemy_knight",
                        "slu:monster_tower_knight"),
                List.of("slu:bad_omen_giant")),
        new Theme("§5Le Trône du Néant — Le Trône qui Regarde en Bas",
                List.of("slu:monster_blasphemy_knight", "slu:magma_giant", "slu:monster_crusader"),
                List.of("slu:havel")),
    };

    public static int count() { return THEMES.length; }

    public static Theme forFloor(int floor) {
        if (floor <= 0) return THEMES[0];
        return THEMES[(floor - 1) % THEMES.length];
    }
}
